name: "Infrastructure de production"
description: "TP du module Infrastructure de production de l'université d'Orléans"
markdown: kramdown

logo: /assets/icon.png
author:
  name: MOULRON Diogène
  email: diogene.moulron@laposte.net
copyright:  © 2020. All rights reserved.

incremental: false
highlighter: rouge
gist:
  noscript: false

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true

compress_html:
  comments:            ['<!-- ', ' -->']
  clippings:           all
  endings:             all

sass:
  style: compressed

theme: jekyll-theme-hydejack

plugins:
  # - jekyll-avatar
  # - jekyll-default-layout
  - jekyll-feed
  # - jekyll-gist
  # - jekyll-optional-front-matter
  - jekyll-paginate
  # - jekyll-readme-index
  # - jekyll-redirect-from
  - jekyll-relative-links
  # - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-titles-from-headings


relative_links:
  enabled: true
  collections: true
  include:
    - readme.md
    - tps/TP1/readme.md