
server:
  port: 0   
logging:
  level:
    org:
      springframework: DEBUG
      

---
spring:
  profiles: simple

server:
  port: ${PORT:8080} 
logging:
  level:
    org:
      springframework: DEBUG