spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/{segment}
          filters:
            - AddRequestHeader=Authorization, Basic YWRtaW46ZGVtbw==
            - SetPath=/api/{segment}
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2

server:
  port: 0

---
spring:
  profiles: simple
  cloud:
    gateway:
      enabled: true
      routes:
        - id: vets-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/vet/{segment}
          filters:
            - BasicRequestHeader=admin, $\{vet.service.password}
            - SetPath=/api/{segment}
        - id: visits-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2

server:
  port: ${PORT:8080}
logging:
  level:
    org:
      springframework: DEBUG