spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2

server:
  port: 0   
logging:
  level:
    org:
      springframework: DEBUG
      

---
spring:
  profiles: simple
  cloud:
    gateway:
      enabled: true
      routes:
        - id: vets-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2

server:
  port: ${PORT:8080}