server:
  port: 0
petclinic:
  database: hsqldb
spring:
  datasource:
    schema: classpath*:db/${petclinic.database}/schema.sql
    data: classpath*:db/${petclinic.database}/data.sql
logging: 
  level: 
    org:
      springframework: INFO